### ISSUE TITLE
enzyme plugin - superplate-cli has encountered an error.

### ISSUE THREAD

**Issue by tpinne** [pankod/superplate#239]
```
$ npx superplate-cli my-project
Need to install the following packages:
  superplate-cli
Ok to proceed? (y)
✔ Cloned remote source successfully.
✔ What will be the name of your app · my-project
✔ Package manager: · yarn
✔ UI framework: · tailwind
✔ CSS Preprocessor: · css
✔ Features: · fetch,env,bundle-analyzer,graphql-request
✔ Hooks · swr,react-use
✔ State Management: · none
✔ i18n - Internationalization · next-translate
✔ Linting tools: · eslint,prettier
✔ Do you want to use lint-staged? · lint-staged
✔ Testing Framework: · enzyme
✔ E2E Testing framework: · cypress
✔ Docker integration: · none
✔ Continuous integration: · github-actions
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR ReferenceError: ejs:3
    1| import React, { ReactNode } from "react";
    2| import { mount as mountBase, MountRendererProps, ReactWrapper } from "enzyme";
 >> 3| <%- testSetup ? testSetup.import ? testSetup.import.join("\n") : "" : "" %>
    4|
    5| <%
    6|     var top = testSetup ? testSetup.wrapper ? testSetup.wrapper.map(wrapper => wrapper[0] || "") : [] : [];

testSetup is not defined
    at SAO.eval (eval at compile (/Users/tpp/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:471:14), <anonymous>:12:17)
    at anonymous (/Users/tpp/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:495:19)
    at Object.exports.render (/Users/tpp/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:313:39)
    at /Users/tpp/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:988:60
    at Array.forEach (<anonymous>)
    at /Users/tpp/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:985:20
    at /Users/tpp/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.pY_v_9Te.js:7629:51
    at async Majo.process (/Users/tpp/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.pY_v_9Te.js:7674:7)
    at async Majo.dest (/Users/tpp/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.pY_v_9Te.js:7694:7)
    at async runActions (/Users/tpp/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:997:7) {
  path: ''
}
```

**Comment by CitizenAERG** [comment]
I'm encountering the same issue since yesterday. 
Currently looking into it.

**Comment by omeraplak** [comment]
Hello @tpinne ,
Thank you for report the issue. We've [fixed](https://github.com/pankod/superplate-core-plugins/issues/199) on core plugins. Could you try again?

Hello @CitizenAERG,
node@15 support is another issue. We are working on it node@15 support. Thank you for trying to help. 🥳
