### ISSUE TITLE
Error : Failed to install

### ISSUE THREAD

**Issue by JeremyMesca** [pankod/superplate#241]
Hello world! 😄 

When i want to start a project with npx superplate-cli, i triggered this error : 

```
✔ Cloned remote source successfully.
✔ What will be the name of your app · test
✔ Package manager: · yarn
✔ UI framework: · tailwind
✔ CSS Preprocessor: · scss
✔ Features: · fetch,axios
✔ Hooks · 
✔ State Management: · redux
✔ i18n - Internationalization · none
✔ Linting tools: · eslint,prettier
✔ Do you want to use lint-staged? · none
✔ Testing Framework: · jest
✔ E2E Testing framework: · none
✔ Docker integration: · none
✔ Continuous integration: · none
warning ../../../package.json: No license field
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer supported
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning jest > @jest/core > jest-haste-map > sane > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
error jest-worker@27.0.0-next.5: The engine "node" is incompatible with this module. Expected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.13.1"
error Found incompatible module.


superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /Users/someone/Desktop/test/test
    at ChildProcess.<anonymous> (/Users/someone/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1047:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  sao: true
}

```

thank's 😄

**Comment by JeremyMesca** [comment]
Update : fonctionne très bien avec npm.
