### ISSUE TITLE
superplate-cli has encountered an error.

### ISSUE THREAD

**Issue by yoiang** [pankod/superplate#267]
Hello! I am running into this crash when I've tried using the cli:
Node: v14.17.1

```sh
✔ Cloned remote source successfully.
✔ Select your project type › nextjs
✔ What will be the name of your app · sample_app
✔ UI framework: · bootstrap
✔ CSS Preprocessor: · styled-components
✔ Do you also want to add styled-system ? · none
✔ Features: · axios,storybook,svgr,env,bundle-analyzer
✔ Hooks · react-query
✔ State Management: · none
✔ i18n - Internationalization · next-translate
✔ Linting tools: ·
✔ Testing Framework: · testing-library
✔ E2E Testing framework: · cypress
✔ Docker integration: · none
✔ Continuous integration: · none
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /Users/username/sample_app
    at ChildProcess.<anonymous> (/Users/username/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:375:28)
    at Pipe.<anonymous> (net.js:675:12) {
  sao: true
}

**Comment by yoiang** [comment]
Is there a verbose output mode? That would help narrowing down the issue in the future!

After many permutations it looks like `styled-components` was the culprit, not selecting it causes the installation to move forward.

**Comment by omeraplak** [comment]
Hi @yoiang ,
Thank you for contacting us. We've fixed your issue and release 1.2.2. Could you try again?

**Comment by naquiroz** [comment]
For me the issue was styled-system

**Comment by kevnoutsawo** [comment]
Hello,
I am facing the same issue. Has a solution been found yet?

✔ Downloaded remote source successfully.
✔ Choose a project template · refine-react
✔ What would you like to name your project?: · client
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · mui
✔ Do you want to add example pages?: · inferencer
✔ Do you need any Authentication logic?: · auth-provider-google
✔ Do you need i18n (Internationalization) support?: · no
✔ Choose a package manager: · npm
✔ Would you mind sending us your choices so that we can improve superplate? · yes
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /home/kevin/Projects/refine_dashboard/client
    at ChildProcess.<anonymous> (/home/kevin/.npm/_npx/98c66fac912b1cba/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  sao: true
}

I have tried using different connections and even a VPN as someone mentioned that is another issue but to no avail.
Thanks in advance.

**Comment by kevnoutsawo** [comment]
I could make it work by choosing yarn instead of npm as package manager when prompted.

**Comment by Busilancer** [comment]
I have a similar error. Some help please

superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues
ERROR SAOError: Failed to install packages in C:\Users\dompa\Desktop\refine-dashboard/client
    at ChildProcess.<anonymous> (C:\Users\dompa\AppData\Local\npm-cache\_npx\98c66fac912b1cba\node_modules\sao\dist\chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (C:\Users\dompa\AppData\Local\npm-cache\_npx\98c66fac912b1cba\node_modules\sao\dist\chunk.T-GsVNZ1.js:460:27)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  sao: true
}

**Comment by GiantCoder** [comment]
I got the same error using either npm or yarn:
`ERROR SAOError: Failed to install packages in /Users/mattotoole/Documents/code/react/refine-dashboard
    at ChildProcess.<anonymous> (/Users/mattotoole/.npm/_npx/98c66fac912b1cba/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (events.js:376:20)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  sao: true
}`
