### ISSUE TITLE
Failed to install with spaces in path

### ISSUE THREAD

**Issue by yoiang** [pankod/superplate#268]
It looks like a command to run `prettier` fails as part of the install. I've adjusted the anonymized the path below:

superplate-cli has encountered an error.
```sh
If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR Error: Command failed: npx prettier /Users/username/Documents/my path/has spaces/project --write
npm WARN exec The following package was not found and will be installed: prettier
[error] No files matching the pattern were found: "/Users/username/Documents/my".
[error] No files matching the pattern were found: "path/has".
[error] No files matching the pattern were found: "spaces/project".

    at ChildProcess.exithandler (child_process.js:319:12)
    at ChildProcess.emit (events.js:375:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'npx prettier /Users/username/Documents/Documents/my path/has spaces/project --write',
  stdout: '',
  stderr: 'npm WARN exec The following package was not found and will be installed: prettier\n' +
    '[error] No files matching the pattern were found: "/Users/username/Documents/my".\n' +
    '[error] No files matching the pattern were found: "path/has".\n' +
    '[error] No files matching the pattern were found: "spaces/project".\n'
}
```

**Comment by omeraplak** [comment]
Hi @yoiang ,
Thank you for contacting us. We've fixed your issue and release 1.2.2. Could you try again?
