### ISSUE TITLE
I get an error while creating a react project called Unexpected token '.'

### ISSUE THREAD

**Issue by feyzullahyildiz** [pankod/superplate#274]
Here is a bug while I am creating a react project.

node version: v12.20.1
OS: windows 10
superplate-cli version: 1.2.2

```
PS C:\Users\feyzullah\Desktop\projects> npx superplate-cli test
npx: installed 138 in 6.723s
✔ Cloned remote source successfully.
√ Select your project type » react
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR C:\Users\FEYZUL~1\AppData\Local\Temp\d-2021720-3080-oji79g.1qmq\react\prompt.js:201
                return !answers.features?.includes("storybook");
                                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at SAO.prompts (C:\Users\feyzullah\AppData\Roaming\npm-cache\_npx\3080\node_modules\superplate-cli\lib\saofile.js:28:27)
    at runPrompts (C:\Users\feyzullah\AppData\Roaming\npm-cache\_npx\3080\node_modules\superplate-cli\node_modules\sao\dist\run-prompts.js:19:79)
    at SAO.runGenerator (C:\Users\feyzullah\AppData\Roaming\npm-cache\_npx\3080\node_modules\superplate-cli\node_modules\sao\dist\chunk.T-GsVNZ1.js:7126:13)
PS C:\Users\feyzullah\Desktop\projects> node -v
v12.20.1
PS C:\Users\feyzullah\Desktop\projects> npx superplate-cli --version
npx: installed 138 in 5.566s
1.2.2
PS C:\Users\feyzullah\Desktop\projects>

```

**Comment by albertus-96** [comment]
My friend got the same issue.

We solved it by upgrading the node version to the latest stable (v14).

Try to upgrade it please, let me know if you still got the issue.

**Comment by feyzullahyildiz** [comment]
This is working on node 14 :+1:
