### ISSUE TITLE
ERROR SAOError: Failed to install packages

### ISSUE THREAD

**Issue by Hopeful-ly** [pankod/superplate#291]
While generating a project with superplate, this an error occured.
here's the full terminal outputs:
```bash
PS C:\Users\himas\Documents\Programming\DiscordFa> npx superplate-cli bots
Need to install the following packages:
  superplate-cli
Ok to proceed? (y) y
✔ Cloned remote source successfully.
√ Select your project type » nextjs
√ What will be the name of your app · bots
√ Package manager: · yarn
√ UI framework: · none
√ CSS Preprocessor: · styled-components
√ Do you also want to add styled-system ? · styled-system
√ Features: · axios,storybook,svgr,env,reverse-proxy,bundle-analyzer
√ Hooks · react-query,react-use
√ State Management: · none
√ i18n - Internationalization · next-i18next
√ Linting tools: · prettier
√ Testing Framework: · enzyme
√ E2E Testing framework: · cypress
√ Docker integration: · Docker
√ Continuous integration: · github-actions
warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSear
warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSear
warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSear
chParams API instead.
warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should us
warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSear
chParams API instead.
warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should us
warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSear
chParams API instead.
warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should us
e the URLSearchParams API instead.
warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSear
chParams API instead.
warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should us
e the URLSearchParams API instead.
warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSear
chParams API instead.
warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should us
e the URLSearchParams API instead.
warning storybook-addon-styled-component-theme > recompose > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer m
aintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection i
n old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencie
s to the actual version of core-js.
warning storybook-addon-styled-component-theme > recompose > fbjs > core-js@1.2.7: core-js@<3.3 is no longer maintained
and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core
-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the a
ctual version of core-js.
warning @storybook/addon-essentials > @storybook/addon-docs > @jest/transform > jest-haste-map > sane@4.1.0: some depend
ency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning @storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > webpack-hot-middleware > que
rystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > webpack > watchpack > watchp
ack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > webpack > watchpack > watchp
ack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upg
rade to fsevents 2.
warning @storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > webpack-dev-middleware > web
warning next > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSear
chParams API instead.
warning next > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legacy. new code should us
e the URLSearchParams API instead.
warning storybook-addon-styled-component-theme > recompose > babel-runtime > core-js@2.6.12: core-js@<3.3 is no longer m
aintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection i
n old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencie
s to the actual version of core-js.
warning storybook-addon-styled-component-theme > recompose > fbjs > core-js@1.2.7: core-js@<3.3 is no longer maintained
and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core
-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the a
ctual version of core-js.
warning @storybook/addon-essentials > @storybook/addon-docs > @jest/transform > jest-haste-map > sane@4.1.0: some depend
ency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
warning @storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > webpack-hot-middleware > que
rystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
warning @storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > webpack > watchpack > watchp
ack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > webpack > watchpack > watchp
ack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upg
rade to fsevents 2.
warning @storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > webpack-dev-middleware > web
pack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumst
lease upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to
 be problematic.  See https://v8.dev/blog/math-random for details.
warning @storybook/addon-essentials > @storybook/addon-docs > @jest/transform > jest-haste-map > sane > micromatch > sna
pdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning @storybook/addon-essentials > @storybook/addon-docs > @jest/transform > jest-haste-map > sane > micromatch > sna
pdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning @storybook/react > @pmmmwh/react-refresh-webpack-plugin > native-url > querystring@0.2.1: The querystring API is
 considered Legacy. new code should use the URLSearchParams API instead.
warning @svgr/cli > @svgr/plugin-svgo > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
warning " > styled-components@5.3.3" has unmet peer dependency "react-is@>= 16.8.0".
warning " > storybook-addon-styled-component-theme@1.3.0" has unmet peer dependency "@storybook/addons@^5.2.0".
warning " > storybook-addon-styled-component-theme@1.3.0" has incorrect peer dependency "@storybook/react@^5.2.0".
warning " > storybook-addon-styled-component-theme@1.3.0" has incorrect peer dependency "styled-components@^4.0.0".
warning "storybook-addon-styled-component-theme > recompose@0.27.1" has incorrect peer dependency "react@^0.14.0 || ^15.
0.0 || ^16.0.0".
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react@15.x || 1
6.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.4" has incorrect peer dependency "react-dom@15.x
|| 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-actions > @storybook/addons > @storybook/router > @reach/router > create-react-context@0.3.0"
has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/components@
^6.3.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/core-events
@^6.3.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/theming@^6.
3.0".
warning " > babel-loader@8.2.3" has unmet peer dependency "webpack@>=2".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-client@6.3.12" has unme
t peer dependency "webpack@*".
warning " > @storybook/preset-scss@1.0.3" has unmet peer dependency "css-loader@*".
warning " > @storybook/preset-scss@1.0.3" has unmet peer dependency "sass-loader@*".
warning " > @storybook/addon-knobs@6.3.1" has unmet peer dependency "@storybook/addons@^6.3.0".
warning " > @storybook/addon-knobs@6.3.1" has unmet peer dependency "@storybook/api@^6.3.0".
warning " > @storybook/addon-knobs@6.3.1" has unmet peer dependency "@storybook/components@^6.3.0".
warning " > @storybook/addon-knobs@6.3.1" has unmet peer dependency "@storybook/core-events@^6.3.0".
warning " > @storybook/addon-knobs@6.3.1" has unmet peer dependency "@storybook/theming@^6.3.0".
warning " > style-loader@2.0.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "@wojtekmaj/enzyme-adapter-react-17 > enzyme-adapter-utils@1.14.0" has incorrect peer dependency "react@0.13.x |
| 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "@wojtekmaj/enzyme-adapter-react-17 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer depend
ency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".


superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in C:\Users\himas\Documents\Programming\DiscordFa\bots
    at ChildProcess.<anonymous> (C:\Users\himas\AppData\Local\npm-cache\_npx\68a94a7f4a156bcd\node_modules\sao\dist\chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:390:28)
    at ChildProcess.cp.emit (C:\Users\himas\AppData\Local\npm-cache\_npx\68a94a7f4a156bcd\node_modules\sao\dist\chunk.T-GsVNZ1.js:460:27)
    at maybeClose (node:internal/child_process:1062:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  sao: true
}
```

Yarn version: `1.22.17`
Node version: `v17.0.1`
Done using Powershell (Not administrator) on Windows 11

**Comment by hcweigand10** [comment]
Also got this error

**Comment by kevnoutsawo** [comment]
Hello,
I am facing the same issue. Has a solution been found yet?

✔ Downloaded remote source successfully.
✔ Choose a project template · refine-react
✔ What would you like to name your project?: · client
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · mui
✔ Do you want to add example pages?: · inferencer
✔ Do you need any Authentication logic?: · auth-provider-google
✔ Do you need i18n (Internationalization) support?: · no
✔ Choose a package manager: · npm
✔ Would you mind sending us your choices so that we can improve superplate? · yes
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /home/kevin/Projects/refine_dashboard/client
    at ChildProcess.<anonymous> (/home/kevin/.npm/_npx/98c66fac912b1cba/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  sao: true
}

Thanks in advance.

**Comment by kevnoutsawo** [comment]
@hcweigand10 @Hopeful-ly I had it working by using pnpm instead of npm. Can you try it?
