### ISSUE TITLE
Error Couldn't find package "js-tokens@^4.0.0"

### ISSUE THREAD

**Issue by duongthaicuong** [pankod/superplate#301]
Please, I got this error with my setting.

RUN: **npx superplate-cli .**
npx: installed 133 in 22.979s

✔ Cloned remote source successfully.
✔ Select your project type › nextjs
✔ What will be the name of your app · next
✔ Package manager: · yarn
✔ UI framework: · chakra-ui
✔ CSS Preprocessor: · scss
✔ Features: · fetch,env,bundle-analyzer
✔ Hooks · swr,react-use
✔ State Management: · none
✔ i18n - Internationalization · none
✔ Linting tools: · eslint,prettier
✔ Do you want to use lint-staged? · none
✔ Testing Framework: · testing-library
✔ E2E Testing framework: · none
✔ Docker integration: · none
✔ Continuous integration: · none

`error Couldn't find package "js-tokens@^4.0.0" required by "@babel/highlight@^7.10.4" o
n the "npm" registry.
ERROR SAOError: Failed to install packages in /Users/macos/next
    at ChildProcess.<anonymous> (/Users/macos/.npm/_npx/22621/lib/node_modules/superplate-cli/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) {
  sao: true
}`

**Comment by kevnoutsawo** [comment]
Hello,
I am facing the same issue. Has a solution been found yet?

```
✔ Downloaded remote source successfully.
✔ Choose a project template · refine-react
✔ What would you like to name your project?: · client
✔ Choose your backend service to connect: · data-provider-custom-json-rest
✔ Do you want to use a UI Framework?: · mui
✔ Do you want to add example pages?: · inferencer
✔ Do you need any Authentication logic?: · auth-provider-google
✔ Do you need i18n (Internationalization) support?: · no
✔ Choose a package manager: · npm
✔ Would you mind sending us your choices so that we can improve superplate? · yes
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in /home/kevin/Projects/refine_dashboard/client
    at ChildProcess.<anonymous> (/home/kevin/.npm/_npx/98c66fac912b1cba/node_modules/sao/dist/chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  sao: true
}
```

Thanks in advance.
