### ISSUE TITLE
pm is not defined

### ISSUE THREAD

**Issue by iicdii** [pankod/superplate#314]
### Bug description
```sh
$ npx superplate-cli my-project
Need to install the following packages:
  superplate-cli@1.7.3
Ok to proceed? (y) y

✔ Cloned remote source successfully.
✔ Package manager: › Npm
✔ Select your project type › nextjs
✔ What will be the name of your app · my-project
✔ UI framework: · antd
✔ CSS Preprocessor: · css
✔ Features: · axios,env,reverse-proxy,bundle-analyzer
✔ Hooks · react-query
✔ State Management: · zustand
✔ i18n - Internationalization · none
✔ Linting tools: · eslint,prettier
✔ Do you want to use lint-staged? · lint-staged
✔ Testing Framework: · testing-library
✔ E2E Testing framework: · cypress
✔ Docker integration: · none
✔ Continuous integration: · github-actions
✔ Would you like to share your choices with us anonymously? › No
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR ReferenceError: ejs:31
    29|           node-version: ${{ matrix.node }}
    30| 
 >> 31| <%_ if (pm === 'yarn') { _%>
    32|       - name: Get yarn cache directory path 
    33|         id: yarn-cache-dir-path
    34|         run: echo "::set-output name=dir::$(yarn cache dir)"

pm is not defined
    at SAO.eval (eval at compile (/Users/harimkims/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:471:14), <anonymous>:12:8)
    at anonymous (/Users/harimkims/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:495:19)
    at Object.exports.render (/Users/harimkims/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:313:39)
    at /Users/harimkims/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:988:60
    at Array.forEach (<anonymous>)
    at /Users/harimkims/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:985:20
    at /Users/harimkims/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.pY_v_9Te.js:7629:51
    at async Majo.process (/Users/harimkims/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.pY_v_9Te.js:7674:7)
    at async Majo.dest (/Users/harimkims/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/chunk.pY_v_9Te.js:7694:7)
    at async runActions (/Users/harimkims/.npm/_npx/68a94a7f4a156bcd/node_modules/sao/dist/run-actions.js:997:7) {
  path: ''
}
```

### System version
- node: v16.17.0
- npm: 8.15.0
- OS: Mac M1 silicon Monterey

**Comment by omeraplak** [comment]
Hey @iicdii ,
Thank you for contacting us! We've released `1.7.4`. Could you approve this fix?
