### ISSUE TITLE
superplate-cli has encountered an error when refine-nextjs

### ISSUE THREAD

**Issue by bakatest-me** [pankod/superplate#322]
superplate-cli has encountered an error when refine-nextjs
✔ Cloned remote source successfully.
✔ What would you like to name your project?: · my-app
✔ Choose your backend service to connect: · data-provider-supabase
✔ Do you want to use a UI Framework?: · mui
✔ Do you want to customize the Material UI theme?: · mui-extend-theme
✔ Do you want to customize the Material UI layout?: · mui-custom-layout
✔ Do you want to add dark mode support?: · mui-dark-mode
✔ Do you need i18n (Internationalization) support?: · i18n-mui
✔ Do you want to add kbar command interface support?: · no
✔ Choose a package manager: · yarn
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR TypeError: Cannot read properties of undefined (reading 'push')
    at Object.extend (/private/var/folders/56/kwqr7d3550g4438v3f1lw1480000gn/T/d-2023010-56550-rifoij.iwf3e/refine-nextjs/plugins/mui/extend.js:53:30)
    at /Users/jamejame/.npm/_npx/79bf0272b244adfc/node_modules/superplate-cli/lib/Helper/plugin/index.js:56:46
    at Array.map (<anonymous>)
    at concatExtend (/Users/jamejame/.npm/_npx/79bf0272b244adfc/node_modules/superplate-cli/lib/Helper/plugin/index.js:52:62)
    at SAO.data (/Users/jamejame/.npm/_npx/79bf0272b244adfc/node_modules/superplate-cli/lib/saofile.js:98:49)
    at SAO.runGenerator (/Users/jamejame/.npm/_npx/79bf0272b244adfc/node_modules/sao/dist/chunk.T-GsVNZ1.js:7130:44)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async SAO.run (/Users/jamejame/.npm/_npx/79bf0272b244adfc/node_modules/sao/dist/chunk.T-GsVNZ1.js:7141:5)
    at async cli (/Users/jamejame/.npm/_npx/79bf0272b244adfc/node_modules/superplate-cli/lib/cli.js:131:3)

**Comment by yildirayunlu** [comment]
Hey @bakatest-me 

We're sorry for this issue, we'll fix it soon.

**Comment by yildirayunlu** [comment]
Can you try again with `npx superplate-cli@latest`.

**Comment by bakatest-me** [comment]
@yildirayunlu oh thanks so much it's work for me
