### ISSUE TITLE
Error installing/creating refine chakra nextjs example

### ISSUE THREAD

**Issue by robby-robby** [pankod/superplate#323]
Hello!
Sorry totally new to this library. I am attempting to use refine wizard, (refine +chakra +nextjs +example) as you can see below. I am getting the following error and am having trouble tracing it. Any ideas?

Cheers!
And thank you for all your work :) 

```
debug Retrived answers: {
  name: 'modern-lined',
  'data-provider': 'data-provider-custom-json-rest',
  'ui-framework': 'chakra',
  inferencer: 'inferencer',
  'inferencer-headless': 'no',
  'antd-dark-mode': 'no',
  'mui-extend-theme': 'no',
  'antd-custom-layout': 'no',
  'mui-custom-layout': 'no',
  'mantine-custom-layout': 'no',
  'chakra-custom-layout': 'chakra-custom-layout',
  'mui-dark-mode': 'no',
  'mantine-dark-mode': 'no',
  'chakra-dark-mode': 'no',
  'auth-provider': 'auth-provider-custom',
  'i18n-no': 'no',
  'i18n-antd': 'no',
  'i18n-mui': 'no',
  'i18n-mantine': 'no',
  'i18n-chakra': 'no',
  'command-palette': 'no',
  'partytown-builder': 'no',
  npmClient: 'yarn'
}
debug Cached prompt answers: {}
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR TypeError: Cannot read properties of undefined (reading 'component')
    at Object.extend (/private/var/folders/_9/p8ggjlmn71b0jc_mjp32_nlc0000gn/T/d-2023017-62371-hyjnfu.zkcyr/refine-nextjs/plugins/inferencer/extend.js:45:36)
    at /Users/username/.nvm/versions/node/v18.10.0/lib/node_modules/superplate-cli/lib/Helper/plugin/index.js:56:46
    at Array.map (<anonymous>)
    at concatExtend (/Users/username/.nvm/versions/node/v18.10.0/lib/node_modules/superplate-cli/lib/Helper/plugin/index.js:52:62)
    at SAO.data (/Users/username/.nvm/versions/node/v18.10.0/lib/node_modules/superplate-cli/lib/saofile.js:98:49)
    at SAO.runGenerator (/Users/username/.nvm/versions/node/v18.10.0/lib/node_modules/superplate-cli/node_modules/sao/dist/chunk.T-GsVNZ1.js:7130:44)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SAO.run (/Users/username/.nvm/versions/node/v18.10.0/lib/node_modules/superplate-cli/node_modules/sao/dist/chunk.T-GsVNZ1.js:7141:5)
    at async cli (/Users/username/.nvm/versions/node/v18.10.0/lib/node_modules/superplate-cli/lib/cli.js:131:3)
```

**Comment by yildirayunlu** [comment]
Hey @robby-robby,

We publish a release that solves this problem. Can you try with `npx superplate-cli@latest projectName` 🚀
