### ISSUE TITLE
Failed to install the packages

### ISSUE THREAD

**Issue by thejuprasad** [pankod/superplate#348]
✔ Downloaded remote source successfully.
√ Choose a project template · refine-react
√ What would you like to name your project?: · client
? Choose your backend service to connect: ... 
√ Choose your backend service to connect: · data-provider-custom-json-rest

√ Do you want to use a UI Framework?: · mui
√ Do you want to add example pages?: · inferencer
√ Do you need any Authentication logic?: · auth-provider-google       
√ Do you need i18n (Internationalization) support?: · no
superplate-cli has encountered an error.

If you think this is caused by a bug. Please check out:
https://github.com/pankod/superplate/issues

ERROR SAOError: Failed to install packages in C:\Users\tthej\NodeJS\Refine_app/client
    at ChildProcess.<anonymous> (C:\Users\tthej\AppData\Local\npm-cache\_npx\98c66fac912b1cba\node_modules\create-refine-app\node_modules\sao\dist\chunk.T-GsVNZ1.js:6885:16)
    at ChildProcess.emit (node:events:513:28)
    at cp.emit (C:\Users\tthej\AppData\Local\npm-cache\_npx\98c66fac912b1cba\node_modules\create-refine-app\node_modules\sao\dist\chunk.T-GsVNZ1.js:460:27)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  sao: true
}

![image](https://github.com/pankod/superplate/assets/73605401/2268ef2b-31bc-40bc-b292-86dd1695d0a9)

**Comment by MustafaBongalon** [comment]
how can I get this resolved?

**Comment by MustafaBongalon** [comment]
I encountered the same error, can someone help me out with this issue Plz?

**Comment by BigJoe17** [comment]
Same here 
having same issues

**Comment by HANJAD** [comment]
help us

**Comment by YannKamche** [comment]
I was able to fix it. Here are the couple of things I tried. I don't really know what fixed it but it seemed to work😅
✅Re-installed nodejs and npm in my pc 
✅Re-installed TypeScript and ts-node globally 
           npm install -g typescript.
           npm install -g ts-node.
✅Ensured I had a stable internet connection
✅Set up your refine project again with the command in the video
Hurray. It worked😂
