### ISSUE TITLE
Trying to create a custom refine in nextjs !sao.opts.extras.projectType.includes("refine")

### ISSUE THREAD

**Issue by kalib-code** [pankod/superplate#368]
Trying to create a custom refine in nextjs i just copy the template nextjs  on a separate repo then do some customization on plugins  and wanting to use superplate for cli but having this issue 

/Users/karlkennethalibuas/Project/node_modules/superplate-cli/lib/saofile.js:160
      skip: () => !sao.opts.extras.projectType.includes("refine")
                                               ^

TypeError: Cannot read properties of undefined (reading 'includes')
    at Input.skip (/Users/karlkennethalibuas/Project/node_modules/superplate-cli/lib/saofile.js:160:48)
    at Input.skip (/Users/karlkennethalibuas/Project/node_modules/enquirer/lib/prompt.js:196:46)
    at /Users/karlkennethalibuas/Project/node_modules/enquirer/lib/prompt.js:241:22
    at new Promise (<anonymous>)
    at Input.run (/Users/karlkennethalibuas/Project/node_modules/enquirer/lib/prompt.js:237:12)
    at Enquirer.ask (/Users/karlkennethalibuas/Project/node_modules/enquirer/index.js:141:43)
    at Enquirer.prompt (/Users/karlkennethalibuas/Project/node_modules/enquirer/index.js:85:20)
    at fn (/Users/karlkennethalibuas/Project/node_modules/enquirer/index.js:222:23)
    at SAO.actions (/Users/karlkennethalibuas/Project/node_modules/superplate-cli/lib/saofile.js:155:58)
    at runActions (/Users/karlkennethalibuas/Project/node_modules/sao/dist/run-actions.js:953:79)

**Comment by omeraplak** [comment]
Hey @kalib-code ,
I've released version v1.17.8. Could you please update the latest version and test it?

Thanks

**Comment by kalib-code** [comment]
thanks confirming its workings
